config/routes.rb
Planner::Application.routes.draw do
  resources :contents

  resources :content_categories

  devise_for :users

  resources :activities

  get "planner/index"

  get "catalog/index"

  resources :activity_categories

  get "home/index"

root :to => 'home#index'

  resources :home do
    get 'about', on: :collection
    get 'contact', on: :collection
    get 'admin', on: :collection
  end

  get 'tags/:tag', to: 'catalog#index', as: :tag

end

app/models/content_category.rb
class ContentCategory < ActiveRecord::Base
  attr_accessible :name
  attr_readonly :id
  has_many :contents, dependent: :destroy
  self.per_page = 7
end

app/controllers/content_categories_controller.rb
class ContentCategoriesController < ApplicationController
  before_filter :check_admin

  def index
    @content_categories = ContentCategory.paginate(page: params[:page])
    render layout: false
  end

  def show
    @content_category = ContentCategory.find(params[:id])
  end

  def new
    @content_category = ContentCategory.new
    render layout: false
  end

  def edit
    @content_category = ContentCategory.find(params[:id])
    render layout: false
  end

  def create
    @content_category = ContentCategory.new(params[:content_category])

    respond_to do |format|
      if @content_category.save
        format.html { redirect_to admin_home_index_path, notice: 'Content category was successfully created.' }
        format.json { render json: @content_category, status: :created, location: @content_category }
      else
        format.html { render action: "new" }
        format.json { render json: @content_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /content_categories/1
  # PUT /content_categories/1.json
  def update
    @content_category = ContentCategory.find(params[:id])

    respond_to do |format|
      if @content_category.update_attributes(params[:content_category])
        format.html { redirect_to admin_home_index_path, notice: 'Content category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_categories/1
  # DELETE /content_categories/1.json
  def destroy
    @content_category = ContentCategory.find(params[:id])
    @content_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_home_index_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/content_categories_helper.rb
module ContentCategoriesHelper
end

app/views/content_categories/_form.html.erb
<%= simple_form_for @content_category do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

app/views/content_categories/edit.html.erb
<div class='border-form-div'>
  <span class="label label-inverse in_form">Edit content category</span>
  <%= render 'form' %>
</div>

app/views/content_categories/index.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

  <% @content_categories.each do |content_category| %>
      <tr>
        <td><%= content_category.name %></td>
        <td><a href="#" class="edit_cont_cat" value="<%= content_category.id %>">Edit</a> <%= link_to 'Destroy', content_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @content_categories %>
<br>
<a href="#" id="new_cont_cat">New Content category</a>

app/views/content_categories/new.html.erb
<div class='border-form-div'>
  <span class="label label-inverse in_form">Add new content category</span>
  <%= render 'form' %>
</div>

app/views/content_categories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_content_category_path(@content_category) %> |
<%= link_to 'Back', content_categories_path %>