config/routes.rb
Planner::Application.routes.draw do
  resources :contents

  resources :content_categories

  devise_for :users

  resources :activities

  get "planner/index"

  get "catalog/index"

  resources :activity_categories

  get "home/index"

root :to => 'home#index'

  resources :home do
    get 'about', on: :collection
    get 'contact', on: :collection
    get 'admin', on: :collection
  end

  get 'tags/:tag', to: 'catalog#index', as: :tag

end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :content_category_id, :activity_id, :user_id, :data
  belongs_to :activity
  belongs_to :content_category
  belongs_to :user
  self.per_page = 7
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    @contents = Content.paginate(page: params[:page])
    render layout: false
  end

  def show
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
    @activity = Activity.all
    @category = ContentCategory.all
    @user = User.all
    render layout: false
  end

  def edit
    @content = Content.find(params[:id])
    @activity = Activity.all
    @category = ContentCategory.all
    @user = User.all
    render layout: false
  end

  def create
    @content = Content.new(params[:content])
    respond_to do |format|
      if @content.save
        format.html { redirect_to :back, notice: 'Content was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @content = Content.find(params[:id])
    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to :back, notice: 'Content was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= simple_form_for @content do |f| %>
    <%= f.input :content_category_id, collection: @category, default: params[:content_category_id]%>
    <%= f.input :activity_id, collection: @activity, default: params[:activity_id]%>
    <%= f.input :user_id, collection: @user, default: current_user.id%>
    <%= f.input :data, input_html: { rows: '5'} %>
    <%= f.button :submit, input_html: { class: 'btn btn-primary'} %>
<% end %>

app/views/contents/edit.html.erb
<div class='border-form-div'>
  <span class="label label-inverse in_form">Edit content</span>
  <%= render 'form' %>
</div>

app/views/contents/index.html.erb
<table class="table">
  <tr>
    <th>Category</th>
    <th>Activity</th>
    <th>User</th>
    <th>Data</th>
    <th>Actions</th>
  </tr>

  <% @contents.each do |c| %>
      <tr>
        <td><%= c.content_category.name %></td>
        <td><%= c.activity.name %></td>
        <td><%= c.user.name %></td>
        <td><%= c.data %></td>
        <td><a href="#" class="edit_cont" value="<%= c.id %>">Edit</a> <%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @contents %>
<br>
<a href="#" id="new_cont">New content</a>

app/views/contents/new.html.erb
<div class='border-form-div'>
  <span class="label label-inverse in_form">Add new content</span>
  <%= render 'form' %>
</div>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>