config/routes.rb
Planner::Application.routes.draw do
  resources :contents

  resources :content_categories

  devise_for :users

  resources :activities

  get "planner/index"

  get "catalog/index"

  resources :activity_categories

  get "home/index"

root :to => 'home#index'

  resources :home do
    get 'about', on: :collection
    get 'contact', on: :collection
    get 'admin', on: :collection
  end

  get 'tags/:tag', to: 'catalog#index', as: :tag

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_filter :redir, only: [:edit,:update,:destroy,:show,:new,:create]

  def index
    category = params[:cat_id] || 'all'
    @cats = ActivityCategory.all
    if category != 'all'
      if params[:tag]
        @acts = Activity.tagged_with(params[:tag]).where('activity_category_id = ?', category)
      else
        @acts = Activity.where('activity_category_id = ?', category)
      end
    else
      if params[:tag]
        @acts = Activity.tagged_with(params[:tag])
      else
        @acts = Activity.all
      end
    end
  end

end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/index.html.erb
<div class="row-fluid">
  <div class="span3">
    <!-- Sidebar Holder -->
    <div class="well sidebar-nav">
      <ul class="side_ul"><li class="nav-header">Categories</li></ul>
      <!-- Categories Holder -->
      <ul class="nav nav-list" id="categories_list">
        <li id="all" class="active_category"><a href="#" class="all">All</a></li>
        <% @cats.each do |c| %>
            <li id=<%= c.id %>><a href="#"><%= c.name %></a></li>
        <% end %>
      </ul>
      <!-- /Categories Holder -->
      <hr>
      <ul class="side_ul"><li class="nav-header">Tags</li></ul>

      <div id="myCanvasContainer">
        <canvas id="myCanvas">
          <p>Anything in here will be replaced on browsers that support the canvas element</p>
        </canvas>
      </div>
      <div id="tags">
        <ul>
          <% tag_cloud Activity.tag_counts, %w{s m l} do |tag, css_class| %>
          <li> <%= link_to tag.name, tag_path(tag.name)%></li>
          <% end %>
        </ul>
      </div>
      <ul class="side_ul hidden" id="tag_header"><li class="nav-header">Selected tag</li></ul>
      <div id="selected_tags">
        <ul></ul>
        <a id="clear_tag" class="hidden">Clear tags</a>
      </div>
    </div>

    <!-- /Sidebar Holder -->
  </div>
  <div class="span9">
    <!-- Products Holder -->
    <ul id="products_container" class="thumbnails">
      <% @acts.each do |a| %>
          <li class="span3 product_item" style="margin-left: 10px;">
            <div class="thumbnail" style="height: 205px;">
                <div class="thumb_holder">
                    <a data-toggle="modal" href=#prod<%= a.id %>><img src="../images/temp.jpg"></a>
                </div>
                <div class="caption">
                  <div class="product_sum">
                    <h4><%= a.name %></h4>
                  </div>
                  <div class="product_details_modal modal hide fade" style="display: none;" aria-hidden="true" id=prod<%= a.id %>>
                    <div class="modal-header">
                      <a class="close" data-dismiss="modal">X</a>
                      <div class="caption">
                        <h3><%= a.name %></h3>
                      </div>
                    </div>
                    <div class="modal-body">
                      <p class="four"><%= a.description %></p>
                      <p>Tags: <%= raw a.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
                    </div>
                    <div class="modal-footer"></div>
                  </div>
                  <p>
                    <a class="btn btn-warning" data-toggle="modal" href=#prod<%= a.id %>>
                      <i class="icon-zoom-in"></i>
                      View details
                    </a>
                  </p>
                </div>
            </div>
          </li>
      <% end %>
    </ul>
    <!-- /Products Holder -->
  </div>
</div>
<script src="http://www.goat1000.com/jquery.tagcanvas.min.js" type="text/javascript"></script>
<%= javascript_include_tag "../javascript/catalog.js"%>