config/routes.rb
Planner::Application.routes.draw do
  resources :contents

  resources :content_categories

  devise_for :users

  resources :activities

  get "planner/index"

  get "catalog/index"

  resources :activity_categories

  get "home/index"

root :to => 'home#index'

  resources :home do
    get 'about', on: :collection
    get 'contact', on: :collection
    get 'admin', on: :collection
  end

  get 'tags/:tag', to: 'catalog#index', as: :tag

end

app/models/activity_category.rb
class ActivityCategory < ActiveRecord::Base
  attr_accessible :name
  attr_readonly :id
  has_many :activities, dependent: :destroy
  self.per_page = 7
end

app/controllers/activity_categories_controller.rb
class ActivityCategoriesController < ApplicationController
  before_filter :check_admin

  def index
    @activity_categories = ActivityCategory.paginate(page: params[:page])
    respond_to do |format|
      format.html { render layout: false }
      format.json {
        render json: @activity_categories.select([:name])
      }
    end
  end

  def show
    @activity_category = ActivityCategory.find(params[:id])
  end

  def new
    @activity_category = ActivityCategory.new
    render layout: false
  end

  # GET /activity_categories/1/edit
  def edit
    @activity_category = ActivityCategory.find(params[:id])
    render layout: false
  end

  # POST /activity_categories
  # POST /activity_categories.json
  def create
    @activity_category = ActivityCategory.new(params[:activity_category])

    respond_to do |format|
      if @activity_category.save
        format.html { redirect_to admin_home_index_path({tab: 'B'}), notice: 'Activity category was successfully created.' }
        format.json { render json: @activity_category, status: :created, location: @activity_category }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_categories/1
  # PUT /activity_categories/1.json
  def update
    @activity_category = ActivityCategory.find(params[:id])

    respond_to do |format|
      if @activity_category.update_attributes(params[:activity_category])
        format.html { redirect_to admin_home_index_path({tab: 'B'}), notice: 'Activity category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_categories/1
  # DELETE /activity_categories/1.json
  def destroy
    @activity_category = ActivityCategory.find(params[:id])
    @activity_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_home_index_path({tab: 'B'}) }
      format.json { head :no_content }
    end
  end
end

app/helpers/activity_categories_helper.rb
module ActivityCategoriesHelper
end

app/views/activity_categories/_form.html.erb
<%= simple_form_for @activity_category do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

app/views/activity_categories/edit.html.erb
<div class='border-form-div'>
  <span class="label label-inverse in_form">Edit activity category</span>
    <%= render 'form' %>
</div>

app/views/activity_categories/index.html.erb
<table class="table" id="cat1">
  <thead>
  <tr>
    <th>Name</th>
  </tr>
  </thead>
  <tbody>
  <% @activity_categories.each do |activity_category| %>
      <tr value=<%= activity_category.id %>>
        <td><%= activity_category.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @activity_categories %>
<div class="DTTT_container">
  <a class="DTTT_button DTTT_button_text" id="new_cat">
    <span>New</span>
  </a>
  <a class="DTTT_button DTTT_button_text hidden" id="edit_cat">
    <span>Edit</span>
  </a>
  <a class="DTTT_button DTTT_button_text hidden" id="delete_cat" data-confirm="Are you sure?" data-method="delete" rel="nofollow">
    <span>Delete</span>
  </a>
</div>

app/views/activity_categories/new.html.erb
<div class='border-form-div'>
    <span class="label label-inverse in_form">Add new category</span>
    <%= render 'form' %>
</div>

app/views/activity_categories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_activity_category_path(@activity_category) %> |
<%= link_to 'Back', activity_categories_path %>